[project]
name = "openai-chat-starter"
version = "0.1.0"
description = "A simple example using OpenAI's API"
requires-python = ">=3.12"

dependencies = [
    "openai>=2.9.0"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
